[package]
name = "vocksel/viewport-skybox"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = [
    "David Minnerly <me@vocksel.com>"
]
exclude = [
    "*.spec.lua"
]

[dependencies]
Roact = "roblox/roact@1.4.2"
t = "osyrisrblx/t@3.0.0"
TestEZ = "roblox/testez@0.4.1"